---
# This is an ansible main playbook for the site you deploy
- hosts: local
  sudo: yes
  vars:
    # If development, all error reporting will be detailed etc. If production - production settings apply
    env_name: development

    # The timezone of the server being configureds
    timezone: Europe/Moscow

    # Locale to configure server in
    locale_long: ru_RU
    locale_short: ru

    # Project name in various spelling to substitute into file and folder paths.
    project_name_camel: ThirisCart
    project_name_snake: thiris_cart
    project_name_www: thiris-cart
  roles:
    - role: web
      http_user: "{{ 'vagrant' if env_name == 'development' else 'nginx' }}"
      site_id: {{ project_name_snake }}
      domains:
        - www.{{ project_name_www }}.local
        - {{ project_name_www }}.local
      ssl: no
    - role: postgres
      database: {{ project_name_snake }}
      user: {{ project_name_snake }}
      password: {{ project_name_snake }}
      extensions:
        - citext
    - role: redis
    - role: elastic
    - role: rabbitmq
